### ISSUE TITLE
pip install returning scikit-bio error

### ISSUE THREAD

**Issue by elayton13** [biocore/q2-greengenes2#16]
After installing the latest version of Qiime (2023.2) into a conda environment using the yml file, when I then pip install q2-greengenes2 I get the following error:

ERROR: Could not build wheels for scikit-bio, which is required to install pyproject.toml-based projects

And if I then run qiime --help I don't see the q2-greengenes2 plugin. Does this mean it hasn't installed correctly? Do you have any advice on this? Thank you

**Comment by wasade** [comment]
Hi @elayton13, that is certainly unexpected. I'm surprised q2-greengenes2 is attempting to install skbio as it will already be there from the broader Q2 environment. 

Just to verify, was `pip install q2-greengenes2` performed _within_ the QIIME 2 2023.2 conda environment? The error output here suggests, if I read this right, that the error is relative to a `2022.10` environment

**Comment by elayton13** [comment]
Hi @wasade thanks for getting back to me so quickly. Yes I created the qiime 2023.2 environment with:
conda env create -n qiime2-2023.2 --file qiime2-2023.2-py38-linux-conda.yml
then activated the environment, typed qiime to see the manual page and verify it installed correctly, I then ran pip install q2-greengenes2.  I'm pretty sure 2022.10 is only referring to the anaconda version that I have loaded (I'm working on a HPC facility).

I tried creating a new env with qiime2.2022.8 as you describe on the homepage for this tool. This time the pip install seems to have worked:
Successfully installed nltk-3.8.1 q2-greengenes2-2023.3 redbiom-0.3.9 regex-2023.3.2
However, if I type:
qiime greengenes2
I get:
Error: QIIME 2 has no plugin/command named 'greengenes2'

And I also don't see it on the qiime manual page. Do you have any ideas about what might be going wrong here? Thanks for the help

**Comment by elayton13** [comment]
No worries. I'll attach a txt file for the output of conda list. Actually this time pip install q2-greengenes had the following output which I didn't get before. 
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'PKG-INFO'
Consider using the `--user` option or check the permissions.

And when I used the --user option it seems to have worked:

Collecting q2-greengenes2
  Using cached q2_greengenes2-2023.3-py3-none-any.whl
Collecting scikit-bio
  Using cached scikit_bio-0.5.8-cp39-cp39-linux_x86_64.whl
Collecting iow
  Using cached iow-1.0.6-cp39-cp39-linux_x86_64.whl
Collecting biom-format
  Using cached biom_format-2.1.14-cp39-cp39-linux_x86_64.whl
Collecting redbiom
  Using cached redbiom-0.3.9-py3-none-any.whl
Requirement already satisfied: numpy>=1.9.2 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from biom-format->q2-greengenes2) (1.21.5)
Requirement already satisfied: scipy>=1.3.1 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from biom-format->q2-greengenes2) (1.9.1)
Requirement already satisfied: click in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from biom-format->q2-greengenes2) (8.0.4)
Requirement already satisfied: cython in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from biom-format->q2-greengenes2) (0.29.32)
Requirement already satisfied: h5py in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from biom-format->q2-greengenes2) (3.7.0)
Requirement already satisfied: pandas>=0.20.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from biom-format->q2-greengenes2) (1.4.4)
Requirement already satisfied: nose>=1.3.7 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from iow->q2-greengenes2) (1.3.7)
Collecting hdmedians>=0.14.1
  Using cached hdmedians-0.14.2-cp39-cp39-linux_x86_64.whl
Collecting pandas>=0.20.0
  Using cached pandas-2.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Collecting natsort>=4.0.3
  Using cached natsort-8.3.1-py3-none-any.whl (38 kB)
Requirement already satisfied: IPython>=3.2.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from scikit-bio->q2-greengenes2) (7.31.1)
Requirement already satisfied: decorator>=3.4.2 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from scikit-bio->q2-greengenes2) (5.1.1)
Collecting lockfile>=0.10.2
  Using cached lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting CacheControl>=0.11.5
  Using cached CacheControl-0.12.11-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: matplotlib>=1.4.3 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from scikit-bio->q2-greengenes2) (3.5.2)
Requirement already satisfied: requests in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from redbiom->q2-greengenes2) (2.28.1)
Requirement already satisfied: joblib in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from redbiom->q2-greengenes2) (1.1.0)
Requirement already satisfied: msgpack in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from redbiom->q2-greengenes2) (1.0.3)
Requirement already satisfied: nltk in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from redbiom->q2-greengenes2) (3.7)
Requirement already satisfied: pygments in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (2.11.2)
Requirement already satisfied: backcall in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.18.1)
Requirement already satisfied: pickleshare in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.7.5)
Requirement already satisfied: matplotlib-inline in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (3.0.20)
Requirement already satisfied: setuptools>=18.5 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (63.4.1)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (4.25.0)
Requirement already satisfied: cycler>=0.10 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (1.4.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (9.2.0)
Requirement already satisfied: pytz>=2020.1 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from pandas>=0.20.0->biom-format->q2-greengenes2) (2022.1)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: regex>=2021.8.3 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from nltk->redbiom->q2-greengenes2) (2022.7.9)
Requirement already satisfied: tqdm in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from nltk->redbiom->q2-greengenes2) (4.64.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from requests->redbiom->q2-greengenes2) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from requests->redbiom->q2-greengenes2) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from requests->redbiom->q2-greengenes2) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from requests->redbiom->q2-greengenes2) (3.3)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from jedi>=0.16->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from pexpect>4.3->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.7.0)
Requirement already satisfied: wcwidth in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.2.5)
Requirement already satisfied: six>=1.5 in /opt/apps/apps/binapps/anaconda3/2022.10/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (1.16.0)
Installing collected packages: lockfile, tzdata, natsort, hdmedians, pandas, CacheControl, scikit-bio, biom-format, redbiom, iow, q2-greengenes2
Successfully installed CacheControl-0.12.11 biom-format-2.1.14 hdmedians-0.14.2 iow-1.0.6 lockfile-0.12.2 natsort-8.3.1 pandas-2.0.1 q2-greengenes2-2023.3 redbiom-0.3.9 scikit-bio-0.5.8 tzdata-2023.3

python -c "import q2_gg2; print(q2_gg2.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'q2_gg2'

and 
python -c "import qiime2; print(qiime2.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'qiime2'

I still don't see it when I type qiime or qiime greengenes-2.

[conda_list.txt](https://github.com/biocore/q2-greengenes2/files/11332003/conda_list.txt)

**Comment by wasade** [comment]
Great thanks. So I think the main issue is that a centralized version of conda is being used, and that is leading to issues installing additional packages. 

First, it looks as though `qiime2` is not actually in your environment after activation, which is certainly unexpected as you've indicated that running `qiime` does work. You should see something qualitatively similar to the following when doing the print in the QIIME 2 import hence the confusion:

```bash
$ python -c "import qiime2; print(qiime2.__file__)"
/Users/dtmcdonald/miniconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/qiime2/__init__.py
```

What would explain this is if your conda environment is using a different Python binary. If so, it may also be using a different `pip`, which would definitely disrupt installation of additional libraries. 

Can you send the output of the following?

```bash
$ which qiime
$ which python
$ which python3
$ which pip
$ which pip3
```

Second, I strongly suspect `pip --user ...` does not interact correctly with conda. If the wrong pip is being used, and we can account for that, the it may be that libraries can be installed. However, I don't really know as if you're using a central conda then you won't have write permissions to modify that environment. 

I've always found centralized conda installations to be really confusing.

**Comment by elayton13** [comment]
Hmmm ok, yes I find it all confusing too! This is the output:

(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ which qiime
~/.conda/envs/qiime2-2023.2/bin/qiime
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ which python
~/.conda/envs/qiime2-2023.2/bin/python
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ which python3
~/.conda/envs/qiime2-2023.2/bin/python3
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ which pip
~/.conda/envs/qiime2-2023.2/bin/pip
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ which pip3
~/.conda/envs/qiime2-2023.2/bin/pip3

**Comment by elayton13** [comment]
Actually if I run that command I do get similar to you sorry, not sure why I didn't before
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ python -c "import qiime2; print(qiime2.__file__)"
/mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages/qiime2/__init__.py

but the other is the same
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ python -c "import q2_gg2; print(q2_gg2.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'q2_gg2'

**Comment by wasade** [comment]
Just to be super safe, now that the environment appears activated (e.g., the `print(qiime2.__file__)` works), could you try rerunning `pip install q2-greengenes2`? The prior pip output suggests the environment may not have been active as that print test didn't work 

Also, did you create the QIIME 2 environment following the QIIME 2 installation instructions? Or was it created some otherway, or by someone else?

**Comment by elayton13** [comment]
I was instructed to load a proxy and then to load anaconda with module load apps/binapps/anaconda3/2022.10. I then followed the qiime instructions (wget and creating the env from the .yml file)

Thanks for all your help so far! I'm also asking the core facility for assistance too. Pip install output is similar:
(qiime2-2023.2) [mfbx4el4@login2 [csf3] qiime_2023]$ pip install q2-greengenes2
Collecting q2-greengenes2
  Using cached q2_greengenes2-2023.3-py3-none-any.whl
Collecting redbiom
  Using cached redbiom-0.3.9-py3-none-any.whl
Requirement already satisfied: iow in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from q2-greengenes2) (1.0.5)
Requirement already satisfied: biom-format in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from q2-greengenes2) (2.1.12)
Requirement already satisfied: scikit-bio in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from q2-greengenes2) (0.5.7)
Requirement already satisfied: click in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from biom-format->q2-greengenes2) (8.1.3)
Requirement already satisfied: h5py in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from biom-format->q2-greengenes2) (2.10.0)
Requirement already satisfied: pandas>=0.20.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from biom-format->q2-greengenes2) (2.0.0)
Requirement already satisfied: cython>=0.29 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from biom-format->q2-greengenes2) (0.29.33)
Requirement already satisfied: scipy>=1.3.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from biom-format->q2-greengenes2) (1.8.1)
Requirement already satisfied: numpy>=1.9.2 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from biom-format->q2-greengenes2) (1.23.5)
Requirement already satisfied: nose>=1.3.7 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from iow->q2-greengenes2) (1.3.7)
Requirement already satisfied: lockfile>=0.10.2 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (0.12.2)
Requirement already satisfied: CacheControl>=0.11.5 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (0.12.11)
Requirement already satisfied: decorator>=3.4.2 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (4.4.2)
Requirement already satisfied: IPython>=3.2.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (8.10.0)
Requirement already satisfied: natsort>=4.0.3 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (8.3.0)
Requirement already satisfied: hdmedians>=0.14.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (0.14.2)
Requirement already satisfied: matplotlib>=1.4.3 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (3.6.0)
Requirement already satisfied: scikit-learn>=0.19.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-bio->q2-greengenes2) (0.24.1)
Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Requirement already satisfied: msgpack in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from redbiom->q2-greengenes2) (1.0.4)
Requirement already satisfied: requests in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from redbiom->q2-greengenes2) (2.28.2)
Requirement already satisfied: joblib in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from redbiom->q2-greengenes2) (1.2.0)
Requirement already satisfied: six in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from h5py->biom-format->q2-greengenes2) (1.16.0)
Requirement already satisfied: pickleshare in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.7.5)
Requirement already satisfied: pexpect>4.3 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (4.8.0)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (3.0.36)
Requirement already satisfied: jedi>=0.16 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.18.2)
Requirement already satisfied: stack-data in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.6.2)
Requirement already satisfied: matplotlib-inline in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.1.6)
Requirement already satisfied: backcall in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.2.0)
Requirement already satisfied: pygments>=2.4.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (2.14.0)
Requirement already satisfied: traitlets>=5 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from IPython>=3.2.0->scikit-bio->q2-greengenes2) (5.9.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (4.38.0)
Requirement already satisfied: packaging>=20.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (23.0)
Requirement already satisfied: contourpy>=1.0.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from matplotlib>=1.4.3->scikit-bio->q2-greengenes2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from pandas>=0.20.0->biom-format->q2-greengenes2) (2022.7.1)
Requirement already satisfied: tzdata>=2022.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from pandas>=0.20.0->biom-format->q2-greengenes2) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from scikit-learn>=0.19.1->scikit-bio->q2-greengenes2) (3.1.0)
Requirement already satisfied: tqdm in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from nltk->redbiom->q2-greengenes2) (4.64.1)
Collecting regex>=2021.8.3
  Using cached regex-2023.3.23-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (771 kB)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from requests->redbiom->q2-greengenes2) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from requests->redbiom->q2-greengenes2) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from requests->redbiom->q2-greengenes2) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from requests->redbiom->q2-greengenes2) (1.26.14)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from jedi>=0.16->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from pexpect>4.3->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.7.0)
Requirement already satisfied: wcwidth in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from prompt-toolkit<3.1.0,>=3.0.30->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.2.6)
Requirement already satisfied: pure-eval in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from stack-data->IPython>=3.2.0->scikit-bio->q2-greengenes2) (0.2.2)
Requirement already satisfied: asttokens>=2.1.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from stack-data->IPython>=3.2.0->scikit-bio->q2-greengenes2) (2.2.1)
Requirement already satisfied: executing>=1.2.0 in /mnt/fls01-home01/mfbx4el4/.conda/envs/qiime2-2023.2/lib/python3.8/site-packages (from stack-data->IPython>=3.2.0->scikit-bio->q2-greengenes2) (1.2.0)
Installing collected packages: regex, nltk, redbiom, q2-greengenes2
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  WARNING: The script nltk is installed in '/mnt/fls01-home01/mfbx4el4/gridware/share/python/2.7.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  WARNING: The script redbiom is installed in '/mnt/fls01-home01/mfbx4el4/gridware/share/python/2.7.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed nltk-3.8.1 q2-greengenes2-2023.3 redbiom-0.3.9 regex-2023.3.23

**Comment by wasade** [comment]
Great!!! That output shows `Successfully installed nltk-3.8.1 q2-greengenes2-2023.3 redbiom-0.3.9 regex-2023.3.23`. Within the activated QIIME 2 environment, does the greengenes2 plugin now show?

**Comment by elayton13** [comment]
Yeah this is similar to the output I got when I tried the --user option, but it still doesn't show! What happens is when I do pip install after module load apps/binapps/anaconda3/2022.10 I get:
<lots of requirements already satisfied> and then:
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.4
    Uninstalling pandas-1.4.4:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'PKG-INFO'
Consider using the `--user` option or check the permissions.

but if I don't do module load apps/binapps/anaconda3/2022.10 before the pip install then I get the output in my last comment. I also got the successfully installed greengenes message when I tried making a different conda env with an earlier version of qiime. But in neither of these instances could I actually see or use the plug in despite it saying successfully installed, even after closing down my session and starting again. So it seems it is installing somewhere but I can't call on it I guess? Could that make sense?

**Comment by wasade** [comment]
Does it work to install other plugins? What about `pip install empress`? If that doesn't work, then what may be better would be if we open a thread on the QIIME 2 Forum. I have a suspicion this isn't greengenes2 specific

**Comment by elayton13** [comment]
Yes the same thing happens! I get the same messages with and without loading the anaconda module and I still can't see or use the plug in with qiime empress and it isn't listed when I type qiime, despite returning:

Successfully built empress
Installing collected packages: empress
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  WARNING: The script empress is installed in '/mnt/fls01-home01/mfbx4el4/gridware/share/python/2.7.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed empress-1.2.0

Sorry to trouble you with all of this I thought it was specific to this plug-in, seems like some sort of problem with my clusters anaconda and the plug-ins I guess? If you could help me raise it with qiime that would be great!

**Comment by wasade** [comment]
No worries! This stuff gets confusing quickly. Are you registered on the QIIME 2 forum? What I recommend is briefly summarizing the issue, something like "I'm using a system provided installation of Conda. I'm able to install QIIME 2 2023.2 successfully, but have been unable to install additional plugins from `pip`. A further description of what we've tried so far is covered in "https://github.com/biocore/q2-greengenes2/issues/16". Essentially, we can get pip to report a successful installation, however "qiime" does not appear to see the installed plugins."

My username on the form is also `wasade` if you'd like to tag me

**Comment by wasade** [comment]
Ugh, github squashed the URL to this issue. Instead of the "#16", it would be good to use the full URL to this thread
